export interface ProphecyItem {
  id: string;
  theme: 'Identity & Lineage' | 'Birth & Infancy' | 'Ministry & Mission' | 'Passion & Crucifixion' | 'Resurrection & Victory';
  prophecyTitle: string;
  prophecyDescription: string;
  otReference: string;
  otBook: string;
  otPassageKey: string;
  otContext: string;
  otEsvText: string;
  ntReference: string;
  ntBook: string;
  ntPassageKey: string;
  ntFulfillmentNotes: string;
  ntEsvText: string;
  significance: string;
}

export const MESSIANIC_PROPHECIES: ProphecyItem[] = [
  {
    id: 'protoevangelium',
    theme: 'Identity & Lineage',
    prophecyTitle: 'The Seed of the Woman Crushing the Serpent',
    prophecyDescription: 'The initial Gospel promise (Protoevangelium) foretelling that the offspring of the woman will bruise the serpent’s head.',
    otReference: 'Genesis 3:15 (ESV)',
    otBook: 'Genesis',
    otPassageKey: 'GEN.3',
    otContext: 'Spoken by God in the Garden of Eden following the Fall, establishing the inaugural messianic covenant of ultimate redemption.',
    otEsvText: 'I will put enmity between you and the woman, and between your offspring and her offspring; he shall bruise your head, and you shall bruise his heel.',
    ntReference: 'Galatians 4:4 / Luke 1:31–35 (ESV)',
    ntBook: 'Luke',
    ntPassageKey: 'LUK.1',
    ntFulfillmentNotes: 'Fulfilled in the virgin birth and Christ’s incarnation as born of a woman to destroy the works of the devil.',
    ntEsvText: 'And behold, you will conceive in your womb and bear a son, and you shall call his name Jesus. He will be great and will be called the Son of the Most High.',
    significance: 'The foundational root of redemptive history, pointing from the earliest human tragedy to Christ’s victory over Satan.'
  },
  {
    id: 'abrahamic-seed',
    theme: 'Identity & Lineage',
    prophecyTitle: 'Blessing to All Nations Through Abraham’s Offspring',
    prophecyDescription: 'The covenant that through the seed of Abraham all the nations and families of the earth will be blessed.',
    otReference: 'Genesis 22:18 (ESV)',
    otBook: 'Genesis',
    otPassageKey: 'GEN.22',
    otContext: 'God swore by Himself after Abraham’s testing on Mount Moriah, establishing the unbroken covenant line.',
    otEsvText: 'And in your offspring shall all the nations of the earth be blessed, because you have obeyed my voice.',
    ntReference: 'Matthew 1:1 / Luke 3:34 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.1',
    ntFulfillmentNotes: 'Matthew opens the Gospel explicitly tracing Jesus the Messiah as the son of Abraham.',
    ntEsvText: 'The book of the genealogy of Jesus Christ, the son of David, the son of Abraham.',
    significance: 'Authenticates Jesus as the true promised heir of the Abrahamic covenant embracing both Jew and Gentile.'
  },
  {
    id: 'davidic-throne',
    theme: 'Identity & Lineage',
    prophecyTitle: 'An Everlasting Throne in the Royal Line of David',
    prophecyDescription: 'God promises King David that his descendant will establish a kingdom and throne that lasts forever.',
    otReference: '2 Samuel 7:12–13 (ESV)',
    otBook: '2 Samuel',
    otPassageKey: '2SA.7',
    otContext: 'The Davidic Covenant given through the prophet Nathan concerning the eternal temple and ruler.',
    otEsvText: 'I will raise up your offspring after you, who shall come from your body, and I will establish his kingdom. He shall build a house for my name, and I will establish the throne of his kingdom forever.',
    ntReference: 'Luke 1:32–33 / Matthew 1:1 (ESV)',
    ntBook: 'Luke',
    ntPassageKey: 'LUK.1',
    ntFulfillmentNotes: 'Angel Gabriel declares to Mary that the Lord God will give Jesus the throne of his father David forever.',
    ntEsvText: 'The Lord God will give to him the throne of his father David, and he will reign over the house of Jacob forever, and of his kingdom there will be no end.',
    significance: 'Anchors Christ’s royal claim to the throne of Israel and everlasting dominion over all creation.'
  },
  {
    id: 'virgin-birth',
    theme: 'Birth & Infancy',
    prophecyTitle: 'Born of a Virgin Named Immanuel (God With Us)',
    prophecyDescription: 'The miraculous prophetic sign given to the House of David that a virgin would conceive and bear a son.',
    otReference: 'Isaiah 7:14 (ESV)',
    otBook: 'Isaiah',
    otPassageKey: 'ISA.7',
    otContext: 'Given during the Syro-Ephraimite crisis to King Ahaz as an unbreakable divine sign of deliverance.',
    otEsvText: 'Therefore the Lord himself will give you a sign. Behold, the virgin shall conceive and bear a son, and shall call his name Immanuel.',
    ntReference: 'Matthew 1:22–23 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.1',
    ntFulfillmentNotes: 'Matthew cites Isaiah directly regarding Mary’s miraculous conception through the Holy Spirit.',
    ntEsvText: 'All this took place to fulfill what the Lord had spoken by the prophet: "Behold, the virgin shall conceive and bear a son, and they shall call his name Immanuel" (which means, God with us).',
    significance: 'Confirms both the deity and sinless humanity of Christ, entering human history through supernatural conception.'
  },
  {
    id: 'birthplace-bethlehem',
    theme: 'Birth & Infancy',
    prophecyTitle: 'Ruler Born in Bethlehem Ephrathah',
    prophecyDescription: 'Specific geographical foretelling of the humble ancient town from which Israel’s eternal ruler must emerge.',
    otReference: 'Micah 5:2 (ESV)',
    otBook: 'Micah',
    otPassageKey: 'MIC.5',
    otContext: 'Prophecy addressed to tiny Judean clan of Ephrathah during impending Assyrian devastation.',
    otEsvText: 'But you, O Bethlehem Ephrathah, who are too little to be among the clans of Judah, from you shall come forth for me one who is to be ruler in Israel, whose coming forth is from of old, from ancient of days.',
    ntReference: 'Matthew 2:1, 5–6 / Luke 2:4–7 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.2',
    ntFulfillmentNotes: 'Chief priests and scribes cite Micah to King Herod when the Magi arrived inquiring where the Christ was born.',
    ntEsvText: 'Now after Jesus was born in Bethlehem of Judea in the days of Herod the king, behold, wise men from the east came to Jerusalem... For so it is written by the prophet: "And you, O Bethlehem, in the land of Judah, are by no means least among the rulers of Judah..."',
    significance: 'Demonstrates divine sovereignty orchestrating Roman imperial decrees to birth the King exactly where prophesied 700 years prior.'
  },
  {
    id: 'flight-to-egypt',
    theme: 'Birth & Infancy',
    prophecyTitle: 'Called Out of Egypt',
    prophecyDescription: 'The calling of God’s Son out of Egypt, recapitulating Israel’s corporate exodus in the person of Messiah.',
    otReference: 'Hosea 11:1 (ESV)',
    otBook: 'Hosea',
    otPassageKey: 'HOS.11',
    otContext: 'Reflecting on God’s redemptive deliverance of Israel out of Egyptian bondage as His beloved son.',
    otEsvText: 'When Israel was a child, I loved him, and out of Egypt I called my son.',
    ntReference: 'Matthew 2:14–15 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.2',
    ntFulfillmentNotes: 'Joseph takes the young child and his mother to Egypt until the death of Herod.',
    ntEsvText: 'And he rose and took the child and his mother by night and departed to Egypt and remained there until the death of Herod. This was to fulfill what the Lord had spoken by the prophet, "Out of Egypt I called my son."',
    significance: 'Christ stands as the true and faithful Israel, reliving and redeeming the nation’s history without sin.'
  },
  {
    id: 'forerunner-voice',
    theme: 'Ministry & Mission',
    prophecyTitle: 'The Voice in the Wilderness Preparing the Way',
    prophecyDescription: 'A herald crying out in the desert to prepare the way of Yahweh and level paths for the King.',
    otReference: 'Isaiah 40:3 / Malachi 3:1 (ESV)',
    otBook: 'Isaiah',
    otPassageKey: 'ISA.40',
    otContext: 'Isaiah’s message of comfort announcing that God Himself is returning to Zion to shepherd His people.',
    otEsvText: 'A voice cries: "In the wilderness prepare the way of the LORD; make straight in the desert a highway for our God."',
    ntReference: 'Mark 1:2–4 / Matthew 3:1–3 (ESV)',
    ntBook: 'Mark',
    ntPassageKey: 'MRK.1',
    ntFulfillmentNotes: 'Mark opens his entire Gospel applying this prophecy directly to John the Baptist preparing hearts for Jesus.',
    ntEsvText: 'As it is written in Isaiah the prophet, "Behold, I send my messenger before your face, who will prepare your way, the voice of one crying in the wilderness: \'Prepare the way of the Lord, make his paths straight,\'" John appeared, baptizing in the wilderness...',
    significance: 'Points to John’s preparatory baptism and identifies Jesus Christ as Yahweh coming to dwell among His people.'
  },
  {
    id: 'galilee-light',
    theme: 'Ministry & Mission',
    prophecyTitle: 'A Great Light Dawning on Galilee of the Gentiles',
    prophecyDescription: 'The northern lands of Zebulun and Naphtali, first to suffer exile, will see the brilliant light of the Messiah.',
    otReference: 'Isaiah 9:1–2 (ESV)',
    otBook: 'Isaiah',
    otPassageKey: 'ISA.9',
    otContext: 'Following prophecies of judgment and gloom, Isaiah envisions royal light shining on the darkest borders.',
    otEsvText: 'In the former time he brought into contempt the land of Zebulun and the land of Naphtali, but in the latter time he has made glorious the way of the sea, the land beyond the Jordan, Galilee of the nations. The people who walked in darkness have seen a great light.',
    ntReference: 'Matthew 4:12–16 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.4',
    ntFulfillmentNotes: 'When Jesus withdrew to Capernaum by the sea in the territory of Zebulun and Naphtali to begin preaching.',
    ntEsvText: 'And leaving Nazareth he went and lived in Capernaum by the sea... so that what was spoken by the prophet Isaiah might be fulfilled: "The land of Zebulun and the land of Naphtali... the people dwelling in darkness have seen a great light."',
    significance: 'Affirms that Messiah’s public ministry ignited not in priestly Jerusalem palaces, but among humble Galileans.'
  },
  {
    id: 'spirit-anointed-healer',
    theme: 'Ministry & Mission',
    prophecyTitle: 'Anointed with the Spirit to Proclaim Good News and Liberty',
    prophecyDescription: 'The Servant of the Lord empowered by the Holy Spirit to heal the brokenhearted and release captives.',
    otReference: 'Isaiah 61:1–2 (ESV)',
    otBook: 'Isaiah',
    otPassageKey: 'ISA.61',
    otContext: 'The prophetic announcement of the Year of Jubilee and sovereign restorative grace.',
    otEsvText: 'The Spirit of the Lord GOD is upon me, because the LORD has anointed me to bring good news to the poor; he has sent me to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to those who are bound; to proclaim the year of the LORD\'s favor.',
    ntReference: 'Luke 4:16–21 (ESV)',
    ntBook: 'Luke',
    ntPassageKey: 'LUK.4',
    ntFulfillmentNotes: 'Jesus unrolls the scroll in the Nazareth synagogue, reads these verses, and announces: "Today this Scripture has been fulfilled in your hearing."',
    ntEsvText: 'And he rolled up the scroll and gave it back to the attendant and sat down. And the eyes of all in the synagogue were fixed on him. And he began to say to them, "Today this Scripture has been fulfilled in your hearing."',
    significance: 'Christ’s manifesto identifying His divine ordination as the compassionate Prophet and ultimate Jubilee Redeemer.'
  },
  {
    id: 'speaking-in-parables',
    theme: 'Ministry & Mission',
    prophecyTitle: 'Opening His Mouth to Speak in Parables and Hidden Truths',
    prophecyDescription: 'Foretelling that the teacher of Israel would utter dark sayings and reveal mysteries kept secret since creation.',
    otReference: 'Psalm 78:2 (ESV)',
    otBook: 'Psalms',
    otPassageKey: 'PSA.78',
    otContext: 'Asaph’s historical maskil instructing the congregation through parabolic riddles of God’s covenant works.',
    otEsvText: 'I will open my mouth in a parable; I will utter dark sayings from of old.',
    ntReference: 'Matthew 13:34–35 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.13',
    ntFulfillmentNotes: 'Jesus taught the crowds strictly through parables to fulfill what was spoken through the prophet.',
    ntEsvText: 'All these things Jesus said to the crowds in parables; indeed, he said nothing to them without a parable. This was to fulfill what was spoken by the prophet: "I will open my mouth in parables; I will utter what has been hidden since the foundation of the world."',
    significance: 'Explains the pedagogical method of Jesus, unveiling kingdom truths to disciples while concealing them from hardened critics.'
  },
  {
    id: 'triumphal-entry',
    theme: 'Ministry & Mission',
    prophecyTitle: 'The Gentle King Entering Zion Riding on a Donkey',
    prophecyDescription: 'Zion’s King arriving righteous and having salvation, yet humble and seated on a colt.',
    otReference: 'Zechariah 9:9 (ESV)',
    otBook: 'Zechariah',
    otPassageKey: 'ZEC.9',
    otContext: 'Messianic vision of peace over weapons of war and the global reign of the peaceful King.',
    otEsvText: 'Rejoice greatly, O daughter of Zion! Shout aloud, O daughter of Jerusalem! Behold, your king is coming to you; righteous and having salvation is he, humble and mounted on a donkey, on a colt, the foal of a donkey.',
    ntReference: 'Matthew 21:4–5 / John 12:14–15 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.21',
    ntFulfillmentNotes: 'Fulfilled precisely on Palm Sunday as Jesus entered Jerusalem amid waving palm branches.',
    ntEsvText: 'This took place to fulfill what was spoken by the prophet, saying, "Say to the daughter of Zion, \'Behold, your king is coming to you, humble, and mounted on a donkey, on a colt, the foal of a beast of burden.\'"',
    significance: 'Defines the character of Christ’s kingdom: not conqueror with military chariot, but gentle Savior on a beast of burden.'
  },
  {
    id: 'betrayed-for-thirty-pieces',
    theme: 'Passion & Crucifixion',
    prophecyTitle: 'Betrayed for Thirty Pieces of Silver Cast into the Temple',
    prophecyDescription: 'The shepherd of Israel valued at thirty pieces of silver, which are thrown into the house of the Lord for the potter.',
    otReference: 'Zechariah 11:12–13 (ESV)',
    otBook: 'Zechariah',
    otPassageKey: 'ZEC.11',
    otContext: 'Zechariah acting out the rejected shepherd asking for his wage and receiving the legal value of a wounded slave.',
    otEsvText: 'Then I said to them, "If it seems good to you, give me my wages; but if not, keep them." And they weighed out as my wages thirty pieces of silver. Then the LORD said to me, "Throw it to the potter"—the lordly price at which I was priced by them. So I took the thirty pieces of silver and threw them into the house of the LORD, to the potter.',
    ntReference: 'Matthew 26:15; 27:3, 9–10 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.27',
    ntFulfillmentNotes: 'Judas Iscariot bargains with chief priests for thirty silver coins, later throwing them into the sanctuary before the field was bought.',
    ntEsvText: 'Then Judas, his betrayer, seeing that Jesus was condemned, repented and brought back the thirty pieces of silver... throwing down the pieces of silver into the temple, he departed... Then was fulfilled what had been spoken by the prophet...',
    significance: 'Chilling prophetic precision detailing the exact transaction, location of disposal, and acquisition of the potter’s field.'
  },
  {
    id: 'silent-before-accusers',
    theme: 'Passion & Crucifixion',
    prophecyTitle: 'Silent and Uncomplaining Like a Lamb Led to the Slaughter',
    prophecyDescription: 'The Suffering Servant oppressed and afflicted, yet opening not His mouth before His slaughterers.',
    otReference: 'Isaiah 53:7 (ESV)',
    otBook: 'Isaiah',
    otPassageKey: 'ISA.53',
    otContext: 'The core of Isaiah’s Fourth Servant Song detailing the substitutionary sin-bearing sacrifice.',
    otEsvText: 'He was oppressed, and he was afflicted, yet he opened not his mouth; like a lamb that is led to the slaughter, and like a sheep that before its shearers is silent, so he opened not his mouth.',
    ntReference: 'Matthew 27:12–14 / Mark 15:4–5 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.27',
    ntFulfillmentNotes: 'Before the chief priests, elders, and Governor Pontius Pilate, Jesus gave no answer, causing the governor to marvel.',
    ntEsvText: 'But when he was accused by the chief priests and elders, he gave no answer. Then Pilate said to him, "Do you not hear how many things they testify against you?" But he gave him no answer, not even to a single charge, so that the governor was greatly amazed.',
    significance: 'Showcases Jesus’ voluntary submission to the Father’s redemptive will, offering no self-defense in order to bear our sins.'
  },
  {
    id: 'pierced-hands-feet',
    theme: 'Passion & Crucifixion',
    prophecyTitle: 'Hands and Feet Pierced, Bones Counted',
    prophecyDescription: 'Detailed depiction of agonizing execution where hands and feet are pierced and the victim is encircled by evildoers.',
    otReference: 'Psalm 22:16–17 (ESV)',
    otBook: 'Psalms',
    otPassageKey: 'PSA.22',
    otContext: 'David’s prophetic lament depicting a torment that far exceeded David’s personal life experiences.',
    otEsvText: 'For dogs encompass me; a company of evildoers encircles me; they have pierced my hands and feet—I can count all my bones—they stare and gloat over me.',
    ntReference: 'John 19:18, 37 / Luke 24:39–40 (ESV)',
    ntBook: 'John',
    ntPassageKey: 'JHN.19',
    ntFulfillmentNotes: 'Fulfilled through Roman crucifixion—an execution style unknown in Israel during David’s era.',
    ntEsvText: 'There they crucified him, and with him two others, one on each side, and Jesus between them... And again another Scripture says, "They will look on him whom they have pierced."',
    significance: 'Unmistakable predictive prophecy composed nearly a millennium before the cross became the instrument of death.'
  },
  {
    id: 'divided-garments-lots',
    theme: 'Passion & Crucifixion',
    prophecyTitle: 'Garments Divided and Lots Cast for Clothing',
    prophecyDescription: 'Executioners stripping the sufferer, partitioning garments, and casting lots for his seamless tunic.',
    otReference: 'Psalm 22:18 (ESV)',
    otBook: 'Psalms',
    otPassageKey: 'PSA.22',
    otContext: 'Continued lament of the innocent sufferer at the mercy of callous onlookers.',
    otEsvText: 'They divide my garments among them, and for my clothing they cast lots.',
    ntReference: 'John 19:23–24 / Matthew 27:35 (ESV)',
    ntBook: 'John',
    ntPassageKey: 'JHN.19',
    ntFulfillmentNotes: 'Roman soldiers divided His outer garments into four parts, but cast lots for His seamless tunic.',
    ntEsvText: 'When the soldiers had crucified Jesus, they took his garments and divided them into four parts, one part for each soldier; also his tunic. But the tunic was seamless... so they said to one another, "Let us not tear it, but cast lots for it to see whose it shall be." This was to fulfill the Scripture...',
    significance: 'Eyewitness proof that even callous pagan legionnaires unwittingly carried out ancient Hebrew prophecy to the letter.'
  },
  {
    id: 'gall-and-vinegar',
    theme: 'Passion & Crucifixion',
    prophecyTitle: 'Offered Gall and Sour Wine for Thirst',
    prophecyDescription: 'In His agonizing thirst, the sufferer is mockingly offered bitter gall and vinegar to drink.',
    otReference: 'Psalm 69:21 (ESV)',
    otBook: 'Psalms',
    otPassageKey: 'PSA.69',
    otContext: 'David’s suffering under reproach for God’s house and desperate cry for rescue.',
    otEsvText: 'They gave me poison for food, and for my thirst they gave me sour wine to drink.',
    ntReference: 'Matthew 27:34, 48 / John 19:28–30 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.27',
    ntFulfillmentNotes: 'At Golgotha, soldiers offered Him wine mixed with gall; then to fulfill scripture Jesus cried "I thirst" and received sour wine.',
    ntEsvText: 'They offered him wine to drink, mixed with gall, but when he tasted it, he would not drink it... And one of them at once ran and took a sponge, filled it with sour wine, and put it on a reed and gave it to him to drink.',
    significance: 'Demonstrates Jesus’ full awareness of scriptural fulfillment down to the final breaths of His sacrificial agony.'
  },
  {
    id: 'no-bones-broken',
    theme: 'Passion & Crucifixion',
    prophecyTitle: 'Not One of His Bones Broken',
    prophecyDescription: 'The Passover Lamb and righteous sufferer protected so that not a single bone shall be shattered.',
    otReference: 'Exodus 12:46 / Psalm 34:20 (ESV)',
    otBook: 'Exodus',
    otPassageKey: 'EXO.12',
    otContext: 'The sacred ordinance of the Passover lamb whose flesh protected the Israelites from judgment.',
    otEsvText: 'It shall be eaten in one house; you shall not take any of the flesh outside the house, and you shall not break any of its bones... He keeps all his bones; not one of them is broken.',
    ntReference: 'John 19:33, 36 (ESV)',
    ntBook: 'John',
    ntPassageKey: 'JHN.19',
    ntFulfillmentNotes: 'Soldiers broke the legs of the two thieves to hasten death, but seeing Jesus was already dead, they did not break His legs.',
    ntEsvText: 'But when they came to Jesus and saw that he was already dead, they did not break his legs... For these things took place that the Scripture might be fulfilled: "Not one of his bones will be broken."',
    significance: 'Certifies Jesus as the true, unblemished Paschal Lamb whose blood shields humanity from divine wrath.'
  },
  {
    id: 'buried-with-the-rich',
    theme: 'Passion & Crucifixion',
    prophecyTitle: 'Assigned with Criminals, Yet Buried with the Rich',
    prophecyDescription: 'Though condemned as a transgressor, the Servant is interred in a rich man’s tomb.',
    otReference: 'Isaiah 53:9 (ESV)',
    otBook: 'Isaiah',
    otPassageKey: 'ISA.53',
    otContext: 'Isaiah reflects on the burial and innocence of the Servant who committed no violence or deceit.',
    otEsvText: 'And they made his grave with the wicked and with a rich man in his death, although he had done no violence, and there was no deceit in his mouth.',
    ntReference: 'Matthew 27:57–60 (ESV)',
    ntBook: 'Matthew',
    ntPassageKey: 'MAT.27',
    ntFulfillmentNotes: 'Joseph of Arimathea, a wealthy counselor and disciple, requested Jesus’ body and laid Him in his own new rock-hewn tomb.',
    ntEsvText: 'When it was evening, there came a rich man from Arimathea, named Joseph, who also was a disciple of Jesus... and laid it in his own new tomb, which he had cut in the rock.',
    significance: 'Preserved Christ’s holy body from the ignominy of a criminal dumping pit, initiating the dawn of resurrection glory.'
  },
  {
    id: 'bodily-resurrection',
    theme: 'Resurrection & Victory',
    prophecyTitle: 'Resurrection from the Dead: Flesh Not Seeing Corruption',
    prophecyDescription: 'The Holy One will not be abandoned to Sheol or allowed to undergo decomposition.',
    otReference: 'Psalm 16:10 (ESV)',
    otBook: 'Psalms',
    otPassageKey: 'PSA.16',
    otContext: 'David’s golden song of trust and supreme joy in God’s presence and eternal inheritance.',
    otEsvText: 'For you will not abandon my soul to Sheol, or let your holy one see corruption.',
    ntReference: 'Acts 2:31 / Luke 24:5–7 (ESV)',
    ntBook: 'Luke',
    ntPassageKey: 'LUK.24',
    ntFulfillmentNotes: 'Apostle Peter on Pentecost declares David died and decayed, but foresaw and spoke of the resurrection of the Christ.',
    ntEsvText: 'He foresaw and spoke about the resurrection of the Christ, that he was not abandoned to Hades, nor did his flesh see corruption. This Jesus God raised up, and of that we all are witnesses.',
    significance: 'The hinge of the Christian faith: death is swallowed up in victory through Christ’s physical, incorruptible resurrection.'
  },
  {
    id: 'ascension-exaltation',
    theme: 'Resurrection & Victory',
    prophecyTitle: 'Ascension and Enthronement at God’s Right Hand',
    prophecyDescription: 'The Lord invites King Messiah to sit at His right hand until all enemies become His footstool.',
    otReference: 'Psalm 110:1 (ESV)',
    otBook: 'Psalms',
    otPassageKey: 'PSA.110',
    otContext: 'The most quoted Old Testament verse in the New Testament, establishing the priest-king after Melchizedek.',
    otEsvText: 'The LORD says to my Lord: "Sit at my right hand, until I make your enemies your footstool."',
    ntReference: 'Mark 16:19 / Luke 20:41–44 / Acts 2:34–35 (ESV)',
    ntBook: 'Mark',
    ntPassageKey: 'MRK.16',
    ntFulfillmentNotes: 'Jesus ascended into heaven and sat down at the right hand of the Majesty on high.',
    ntEsvText: 'So then the Lord Jesus, after he had spoken to them, was taken up into heaven and sat down at the right hand of God.',
    significance: 'Proclaims Christ’s supreme cosmic reign and present intercessory priesthood over heaven and earth.'
  }
];

export const THEME_LIST = [
  'All Themes',
  'Identity & Lineage',
  'Birth & Infancy',
  'Ministry & Mission',
  'Passion & Crucifixion',
  'Resurrection & Victory'
] as const;
