import { Disciple } from "./disciples";

export const DISCIPLES_DATA: Disciple[] = [
  {
    id: "peter",
    name: "Simon Peter",
    symbol: "Keys",
    location_of_death: "Rome, Italy",
    year_of_death: "64-67 AD",
    method_of_death: "Crucifixion (Upside Down)",
    narrative:
      "Tradition holds that Peter was crucified in Rome during Nero’s persecution. At his own request, he was crucified head downward, as he felt unworthy to die in the same position as Jesus.",
    reliability_score: 92,
    certainty_level: "High (Early Tradition)",
    scripture_reference: "John 21:18-19",
    sources: JSON.stringify(["Eusebius, Church History", "John 21:18-19", "Clement of Rome"]),
  },
  {
    id: "andrew",
    name: "Andrew",
    symbol: "X-shaped Cross",
    location_of_death: "Patras, Greece",
    year_of_death: "60 AD",
    method_of_death: "Crucifixion",
    narrative:
      "Brother of Peter, Andrew preached in Scythia and Greece. He was reportedly bound, not nailed, to an X-shaped cross (St. Andrew’s Cross) to prolong his suffering.",
    reliability_score: 75,
    certainty_level: "Moderate-High",
    scripture_reference: "Matthew 4:18",
    sources: JSON.stringify(["Acts of Andrew", "Foxe's Book of Martyrs"]),
  },
  {
    id: "james-greater",
    name: "James (Son of Zebedee)",
    symbol: "Scallop Shell",
    location_of_death: "Jerusalem",
    year_of_death: "44 AD",
    method_of_death: "Beheading",
    narrative:
      "The first of the twelve to be martyred. King Herod Agrippa I had him executed by the sword, as recorded in the book of Acts.",
    reliability_score: 100,
    certainty_level: "Scriptural",
    scripture_reference: "Acts 12:2",
    sources: JSON.stringify(["Acts 12:2", "New Living Translation"]),
  },
  {
    id: "john",
    name: "John (Son of Zebedee)",
    symbol: "Eagle",
    location_of_death: "Patmos / Ephesus",
    year_of_death: "c. 100 AD",
    method_of_death: "Natural Causes",
    narrative:
      "The only apostle to likely die of old age. After being exiled to Patmos (where he wrote Revelation), he returned to Ephesus where he died at a very advanced age.",
    reliability_score: 95,
    certainty_level: "Very High",
    scripture_reference: "Revelation 1:9",
    sources: JSON.stringify(["Irenaeus", "Revelation 1:9"]),
  },
  {
    id: "philip",
    name: "Philip",
    symbol: "Cross with Loaves",
    location_of_death: "Phrygia",
    year_of_death: "80 AD",
    method_of_death: "Crucifixion",
    narrative:
      "Philip preached in Phrygia and was reportedly martyred in Hierapolis. Some accounts say he was crucified, others say he was stoned or hung.",
    reliability_score: 65,
    certainty_level: "Tradition",
    scripture_reference: "John 1:43",
    sources: JSON.stringify(["Eusebius", "Acts of Philip"]),
  },
  {
    id: "bartholomew",
    name: "Bartholomew (Nathanael)",
    symbol: "Flaying Knife",
    location_of_death: "Armenia",
    year_of_death: "c. 72 AD",
    method_of_death: "Flayed Alive and Beheaded",
    narrative:
      "Also known as Nathanael. Tradition states he preached in India and Armenia, where he suffered one of the most brutal martyrdoms, being skinned alive.",
    reliability_score: 60,
    certainty_level: "Tradition",
    scripture_reference: "John 1:45",
    sources: JSON.stringify(["Eusebius", "Golden Legend"]),
  },
  {
    id: "thomas",
    name: "Thomas (Didymus)",
    symbol: "Spear",
    location_of_death: "Mylapore, India",
    year_of_death: "72 AD",
    method_of_death: "Speared",
    narrative:
      "Known for his initial doubt, Thomas preached as far as South India. He was reportedly martyred by local priests who ran him through with spears while he was praying.",
    reliability_score: 75,
    certainty_level: "Moderate-High",
    scripture_reference: "John 20:24-29",
    sources: JSON.stringify(["Acts of Thomas", "Syriac Tradition"]),
  },
  {
    id: "matthew",
    name: "Matthew (Levi)",
    symbol: "Money Bag",
    location_of_death: "Ethiopia / Persia",
    year_of_death: "c. 60 AD",
    method_of_death: "Sword / Halberd",
    narrative:
      "The former tax collector preached in Ethiopia and Persia. Most traditions agree he was martyred by the sword, though specific locations vary.",
    reliability_score: 60,
    certainty_level: "Tradition",
    scripture_reference: "Matthew 9:9",
    sources: JSON.stringify(["Heracleon", "Clement of Alexandria"]),
  },
  {
    id: "james-less",
    name: "James (Son of Alphaeus)",
    symbol: "Fuller's Club",
    location_of_death: "Jerusalem",
    year_of_death: "62 AD",
    method_of_death: "Beaten / Stoning",
    narrative:
      "Not to be confused with James the Greater. He was reportedly thrown from the pinnacle of the Temple and then beaten to death with a fuller’s club.",
    reliability_score: 70,
    certainty_level: "Church Tradition",
    scripture_reference: "Mark 3:18",
    sources: JSON.stringify(["Hegesippus", "Josephus"]),
  },
  {
    id: "thaddeus",
    name: "Jude (Thaddeus)",
    symbol: "Axe / Club",
    location_of_death: "Beirut, Lebanon",
    year_of_death: "c. 65 AD",
    method_of_death: "Axe / Club",
    narrative:
      "Also known as Jude. He preached in Mesopotamia and Armenia. He was martyred alongside Simon the Zealot, reportedly killed with an axe or club.",
    reliability_score: 65,
    certainty_level: "Tradition",
    scripture_reference: "Jude 1:1",
    sources: JSON.stringify(["Acts of Simon and Jude", "Golden Legend"]),
  },
  {
    id: "simon-zealot",
    name: "Simon the Zealot",
    symbol: "Saw",
    location_of_death: "Persia / UK",
    year_of_death: "c. 65 AD",
    method_of_death: "Sawed in Half",
    narrative:
      "The most obscure of the twelve. Tradition holds he preached in various regions and was martyred in Persia, often depicted as being sawed in half.",
    reliability_score: 45,
    certainty_level: "Legend / Tradition",
    scripture_reference: "Luke 6:15",
    sources: JSON.stringify(["Golden Legend", "Foxe's Book of Martyrs"]),
  },
  {
    id: "matthias",
    name: "Matthias",
    symbol: "Axe",
    location_of_death: "Jerusalem / Colchis",
    year_of_death: "c. 80 AD",
    method_of_death: "Stoning / Beheading",
    narrative:
      "Chosen to replace Judas Iscariot. He reportedly preached in Judea and was eventually stoned and beheaded.",
    reliability_score: 60,
    certainty_level: "Tradition",
    scripture_reference: "Acts 1:26",
    sources: JSON.stringify(["Acts 1:26", "Clement of Alexandria"]),
  },
];
