-- Migration: Create nodes and edges tables for lineage tree

CREATE TABLE IF NOT EXISTS nodes (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  title TEXT,
  description TEXT,
  scripture_reference TEXT,
  scripture_text TEXT,
  lineage TEXT CHECK(lineage IN ('main', 'royal', 'biological')),
  epoch TEXT,
  x REAL,
  y REAL
);

CREATE TABLE IF NOT EXISTS edges (
  id TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  target TEXT NOT NULL,
  FOREIGN KEY (source) REFERENCES nodes(id),
  FOREIGN KEY (target) REFERENCES nodes(id)
);

CREATE INDEX IF NOT EXISTS idx_nodes_lineage ON nodes(lineage);
CREATE INDEX IF NOT EXISTS idx_nodes_epoch ON nodes(epoch);
CREATE INDEX IF NOT EXISTS idx_edges_source ON edges(source);
CREATE INDEX IF NOT EXISTS idx_edges_target ON edges(target);

-- Seed Lineage Nodes and Edges Data
-- Seed file centered around X=0 with 300px cards

INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('adam', 'Adam', 'The First Man', 'The first human being, created by God in His own image.', 'Genesis 5:3 (NLT)', 'When Adam was 130 years old, he became the father of a son who was just like him—in his very image. He named his son Seth.', 'royal', 'early_patriarchs', -150, 0);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('seth', 'Seth', 'Son of Adam', 'The third son of Adam and Eve, born after the death of Abel.', 'Genesis 5:6 (NLT)', 'When Seth was 105 years old, he became the father of Enosh.', 'royal', 'early_patriarchs', -150, 200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('enosh', 'Enosh', 'Son of Seth', 'Son of Seth; in his time, people first began to worship the Lord by name.', 'Genesis 5:9 (NLT)', 'When Enosh was 90 years old, he became the father of Kenan.', 'royal', 'early_patriarchs', -150, 400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('kenan', 'Kenan', 'Son of Enosh', 'Son of Enosh and a grandson of Seth.', 'Genesis 5:12 (NLT)', 'When Kenan was 70 years old, he became the father of Mahalalel.', 'royal', 'early_patriarchs', -150, 600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('mahalalel', 'Mahalalel', 'Son of Kenan', 'The son of Kenan and father of Jared.', 'Genesis 5:15 (NLT)', 'When Mahalalel was 65 years old, he became the father of Jared.', 'royal', 'early_patriarchs', -150, 800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jared', 'Jared', 'Son of Mahalalel', 'The son of Mahalalel and father of Enoch.', 'Genesis 5:18 (NLT)', 'When Jared was 162 years old, he became the father of Enoch.', 'royal', 'early_patriarchs', -150, 1000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('enoch', 'Enoch', 'One Who Walked with God', 'A man who walked faithfully with God and was taken by God without dying.', 'Genesis 5:21 (NLT)', 'When Enoch was 65 years old, he became the father of Methuselah.', 'royal', 'early_patriarchs', -150, 1200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('methuselah', 'Methuselah', 'Longest Living Man', 'The son of Enoch and the person with the longest lifespan recorded in the Bible.', 'Genesis 5:25 (NLT)', 'When Methuselah was 187 years old, he became the father of Lamech.', 'royal', 'early_patriarchs', -150, 1400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('lamech', 'Lamech', 'Son of Methuselah', 'The son of Methuselah and father of Noah.', 'Genesis 5:28-29 (NLT)', 'When Lamech was 182 years old, he became the father of a son. He named him Noah, for he said, ''May he bring us relief from our work and the painful labor of farming this ground that the Lord has cursed.''', 'royal', 'early_patriarchs', -150, 1600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('noah', 'Noah', 'Builder of the Ark', 'The righteous man who built an ark to save his family and animals from the Great Flood.', 'Genesis 5:32 (NLT)', 'After Noah was 500 years old, he became the father of Shem, Ham, and Japheth.', 'royal', 'early_patriarchs', -150, 1800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('shem', 'Shem', 'Son of Noah', 'One of the three sons of Noah and the ancestor of the Semitic peoples.', 'Genesis 11:10 (NLT)', 'This is the account of Shem’s family. Two years after the great flood, when Shem was 100 years old, he became the father of Arphaxad.', 'royal', 'early_patriarchs', -150, 2000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('arphaxad', 'Arphaxad', 'Son of Shem', 'The son of Shem, born two years after the Great Flood.', 'Genesis 11:12 (NLT)', 'When Arphaxad was 35 years old, he became the father of Shelah.', 'royal', 'early_patriarchs', -150, 2200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('shelah', 'Shelah', 'Son of Arphaxad', 'The son of Arphaxad and father of Eber.', 'Genesis 11:14 (NLT)', 'When Shelah was 30 years old, he became the father of Eber.', 'royal', 'early_patriarchs', -150, 2400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('eber', 'Eber', 'Ancestor of the Hebrews', 'The son of Shelah and the person from whom the name ''Hebrew'' is often thought to be derived.', 'Genesis 11:16 (NLT)', 'When Eber was 34 years old, he became the father of Peleg.', 'royal', 'early_patriarchs', -150, 2600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('peleg', 'Peleg', 'Son of Eber', 'Son of Eber; during his lifetime the earth was divided.', 'Genesis 11:18 (NLT)', 'When Peleg was 30 years old, he became the father of Reu.', 'royal', 'early_patriarchs', -150, 2800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('reu', 'Reu', 'Son of Peleg', 'The son of Peleg and father of Serug.', 'Genesis 11:20 (NLT)', 'When Reu was 32 years old, he became the father of Serug.', 'royal', 'early_patriarchs', -150, 3000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('serug', 'Serug', 'Son of Reu', 'The son of Reu and father of Nahor.', 'Genesis 11:22 (NLT)', 'When Serug was 30 years old, he became the father of Nahor.', 'royal', 'early_patriarchs', -150, 3200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('nahor', 'Nahor', 'Son of Serug', 'The son of Serug and father of Terah.', 'Genesis 11:24 (NLT)', 'When Nahor was 29 years old, he became the father of Terah.', 'royal', 'early_patriarchs', -150, 3400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('terah', 'Terah', 'Father of Abraham', 'The son of Nahor who moved his family from Ur of the Chaldeans toward Canaan.', 'Genesis 11:26 (NLT)', 'After Terah was 70 years old, he became the father of Abram, Nahor, and Haran.', 'royal', 'early_patriarchs', -150, 3600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('abraham', 'Abraham', 'Father of Many Nations', 'Originally named Abram, he was called by God to leave his home and become the father of a great nation.', 'Genesis 12:1 (NLT)', 'The Lord had said to Abram, ''Leave your native country, your relatives, and your father’s family, and go to the land that I will show you.''', 'royal', 'early_patriarchs', -150, 3800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('isaac', 'Isaac', 'Son of Abraham', 'The son of promise born to Abraham and Sarah in their old age, and the second patriarch of Israel.', 'Genesis 25:19 (NLT)', 'This is the account of the family of Isaac, the son of Abraham.', 'royal', 'formation_of_israel', -150, 4000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jacob', 'Jacob', 'Father of the Twelve Tribes', 'The son of Isaac who wrestled with God and was renamed Israel; he was the father of the twelve sons who became the tribes of Israel.', 'Genesis 25:26 (NLT)', 'Then the other twin was born with his hand grasping Esau’s heel. So they named him Jacob. Isaac was sixty years old when the twins were born.', 'royal', 'formation_of_israel', -150, 4200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('judah', 'Judah', 'Son of Jacob', 'The fourth son of Jacob and Leah, whose tribe was prophesied to hold the royal scepter of Israel.', 'Genesis 29:35 (NLT)', 'Once again Leah became pregnant and gave birth to another son. She named him Judah, for she said, ''Now I will praise the Lord!'' And then she stopped having children.', 'royal', 'formation_of_israel', -150, 4400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('perez', 'Perez', 'Son of Judah', 'The son of Judah and Tamar, through whom the lineage leading to King David was continued.', 'Genesis 38:29 (NLT)', 'But then he pulled back his hand, and out came his brother! ''What!'' the midwife exclaimed. ''How did you break out first?'' So he was named Perez.', 'royal', 'formation_of_israel', -150, 4600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('hezron', 'Hezron', 'Son of Perez', 'A grandson of Judah and head of the Hezronite clan who settled in Egypt with the family of Jacob.', 'Ruth 4:18 (NLT)', 'This is the genealogical record of their ancestor Perez: Perez was the father of Hezron.', 'royal', 'formation_of_israel', -150, 4800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('ram', 'Ram', 'Son of Hezron', 'An ancestor of King David who lived during the time the Israelites were in Egypt.', 'Ruth 4:19 (NLT)', 'Hezron was the father of Ram. Ram was the father of Amminadab.', 'royal', 'formation_of_israel', -150, 5000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('amminadab', 'Amminadab', 'Son of Ram', 'The father of Nahshon and an ancestor in the royal line of Judah.', 'Ruth 4:19 (NLT)', 'Ram was the father of Amminadab.', 'royal', 'formation_of_israel', -150, 5200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('nahshon', 'Nahshon', 'Leader of Judah', 'The leader of the tribe of Judah during the Exodus and the wilderness wanderings.', 'Ruth 4:20 (NLT)', 'Amminadab was the father of Nahshon. Nahshon was the father of Salmon.', 'royal', 'formation_of_israel', -150, 5400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('salmon', 'Salmon', 'Son of Nahshon', 'The son of Nahshon who married Rahab and became the father of Boaz.', 'Ruth 4:20 (NLT)', 'Nahshon was the father of Salmon.', 'royal', 'formation_of_israel', -150, 5600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('boaz', 'Boaz', 'Kinsman-Redeemer', 'A wealthy and righteous man of Bethlehem who married Ruth the Moabite, serving as her kinsman-redeemer.', 'Ruth 4:21 (NLT)', 'Salmon was the father of Boaz. Boaz was the father of Obed.', 'royal', 'formation_of_israel', -150, 5800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('obed', 'Obed', 'Son of Boaz and Ruth', 'The son of Boaz and Ruth, and the grandfather of King David.', 'Ruth 4:21 (NLT)', 'Boaz was the father of Obed.', 'royal', 'formation_of_israel', -150, 6000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jesse', 'Jesse', 'Father of David', 'A farmer in Bethlehem and the father of eight sons, the youngest of whom was chosen to be king.', 'Ruth 4:22 (NLT)', 'Obed was the father of Jesse. Jesse was the father of David.', 'royal', 'formation_of_israel', -150, 6200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('david', 'David', 'King of Israel', 'The shepherd boy who defeated Goliath and was anointed by Samuel to become Israel''s greatest king.', '1 Samuel 16:13 (NLT)', 'So as David stood there among his brothers, Samuel took the flask of olive oil he had brought and anointed David with the oil. And the Spirit of the Lord came powerfully upon David from that day on.', 'royal', 'formation_of_israel', -150, 6400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('solomon', 'Solomon', 'King of Israel', 'The son of David and Bathsheba, renowned for his wisdom and for building the first Temple in Jerusalem.', 'Matthew 1:6 (NLT)', 'David was the father of Solomon (whose mother was Bathsheba, the widow of Uriah).', 'royal', 'royal_line', -310, 6600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('rehoboam', 'Rehoboam', 'King of Judah', 'The son of Solomon whose rejection of the people''s request for lighter taxes led to the division of the kingdom.', 'Matthew 1:7 (NLT)', 'Solomon was the father of Rehoboam. Rehoboam was the father of Abijah. Abijah was the father of Asa.', 'royal', 'royal_line', -310, 6800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('abijah', 'Abijah', 'King of Judah', 'The son of Rehoboam who reigned over Judah and continued the war against the northern kingdom of Israel.', 'Matthew 1:7 (NLT)', 'Solomon was the father of Rehoboam. Rehoboam was the father of Abijah. Abijah was the father of Asa.', 'royal', 'royal_line', -310, 7000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('asa', 'Asa', 'King of Judah', 'A king of Judah who was noted for his early religious reforms and his heart being fully committed to the Lord.', 'Matthew 1:8 (NLT)', 'Asa was the father of Jehoshaphat. Jehoshaphat was the father of Jehoram. Jehoram was the father of Uzziah.', 'royal', 'royal_line', -310, 7200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jehoshaphat', 'Jehoshaphat', 'King of Judah', 'The son of Asa who strengthened Judah and walked in the ways of his father by seeking the Lord.', 'Matthew 1:8 (NLT)', 'Asa was the father of Jehoshaphat. Jehoshaphat was the father of Jehoram. Jehoram was the father of Uzziah.', 'royal', 'royal_line', -310, 7400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jehoram', 'Jehoram', 'King of Judah', 'The son of Jehoshaphat who married Athaliah, the daughter of Ahab, and led Judah into idolatry.', 'Matthew 1:8 (NLT)', 'Asa was the father of Jehoshaphat. Jehoshaphat was the father of Jehoram. Jehoram was the father of Uzziah.', 'royal', 'royal_line', -310, 7600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('uzziah', 'Uzziah', 'King of Judah', 'Also known as Azariah, he was a powerful king who reigned for fifty-two years but was later struck with leprosy.', 'Matthew 1:9 (NLT)', 'Uzziah was the father of Jotham. Jotham was the father of Ahaz. Ahaz was the father of Hezekiah.', 'royal', 'royal_line', -310, 7800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jotham', 'Jotham', 'King of Judah', 'The son of Uzziah who grew powerful because he walked steadfastly before the Lord his God.', 'Matthew 1:9 (NLT)', 'Uzziah was the father of Jotham. Jotham was the father of Ahaz. Ahaz was the father of Hezekiah.', 'royal', 'royal_line', -310, 8000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('ahaz', 'Ahaz', 'King of Judah', 'A wicked king of Judah who refused to trust in God and instead sought help from the king of Assyria.', 'Matthew 1:9 (NLT)', 'Uzziah was the father of Jotham. Jotham was the father of Ahaz. Ahaz was the father of Hezekiah.', 'royal', 'royal_line', -310, 8200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('hezekiah', 'Hezekiah', 'King of Judah', 'One of the most prominent kings of Judah, known for his religious reforms and his reliance on God during the Assyrian siege.', 'Matthew 1:10 (NLT)', 'Hezekiah was the father of Manasseh. Manasseh was the father of Amon. Amon was the father of Josiah.', 'royal', 'royal_line', -310, 8400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('manasseh', 'Manasseh', 'King of Judah', 'The son of Hezekiah who reigned longer than any other king of Judah; he was initially wicked but repented in captivity.', 'Matthew 1:10 (NLT)', 'Hezekiah was the father of Manasseh. Manasseh was the father of Amon. Amon was the father of Josiah.', 'royal', 'royal_line', -310, 8600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('amon', 'Amon', 'King of Judah', 'The son of Manasseh who abandoned the Lord and was assassinated by his own officials after a short reign.', 'Matthew 1:10 (NLT)', 'Hezekiah was the father of Manasseh. Manasseh was the father of Amon. Amon was the father of Josiah.', 'royal', 'royal_line', -310, 8800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('josiah', 'Josiah', 'King of Judah', 'The boy-king who initiated a major reformation after the Book of the Law was found in the Temple.', 'Matthew 1:11 (NLT)', 'Josiah was the father of Jehoiachin and his brothers (born at the time of the exile to Babylon).', 'royal', 'royal_line', -310, 9000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jehoiachin', 'Jehoiachin', 'King of Judah', 'The son of Jehoiakim (called Jehoiachin in Matthew) who was taken captive to Babylon; he is the last king in the royal line before the exile.', 'Matthew 1:11 (NLT)', 'Josiah was the father of Jehoiachin and his brothers (born at the time of the exile to Babylon).', 'royal', 'royal_line', -310, 9200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('shealtiel_matthew', 'Shealtiel', 'Son of Jehoiachin', 'The son of Jehoiachin, born during the Babylonian exile, through whom the Davidic line continued.', 'Matthew 1:12 (NLT)', 'After the Babylonian exile: Jehoiachin was the father of Shealtiel. Shealtiel was the father of Zerubbabel.', 'royal', 'royal_line', -310, 9400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('zerubbabel_matthew', 'Zerubbabel', 'Governor of Judah', 'The leader of the first return of exiles from Babylon who laid the foundation of the second Temple.', 'Matthew 1:13 (NLT)', 'Zerubbabel was the father of Abiud. Abiud was the father of Eliakim. Eliakim was the father of Azor.', 'royal', 'royal_line', -310, 9600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('abiud', 'Abiud', 'Son of Zerubbabel', 'An ancestor of Jesus in the royal line of David following the return from Babylonian exile.', 'Matthew 1:13 (NLT)', 'Zerubbabel was the father of Abiud. Abiud was the father of Eliakim. Eliakim was the father of Azor.', 'royal', 'royal_line', -310, 9800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('eliakim_matthew', 'Eliakim', 'Son of Abiud', 'An ancestor in the royal genealogy of Jesus Christ, as recorded by the Apostle Matthew.', 'Matthew 1:13 (NLT)', 'Zerubbabel was the father of Abiud. Abiud was the father of Eliakim. Eliakim was the father of Azor.', 'royal', 'royal_line', -310, 10000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('azor', 'Azor', 'Son of Eliakim', 'A descendant of David in the royal line leading to the Messiah.', 'Matthew 1:14 (NLT)', 'Azor was the father of Zadok. Zadok was the father of Akim. Akim was the father of Eliud.', 'royal', 'royal_line', -310, 10200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('zadok_matthew', 'Zadok', 'Son of Azor', 'An ancestor of Jesus Christ, not to be confused with the high priests of the same name.', 'Matthew 1:14 (NLT)', 'Azor was the father of Zadok. Zadok was the father of Akim. Akim was the father of Eliud.', 'royal', 'royal_line', -310, 10400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('akim', 'Akim', 'Son of Zadok', 'An ancestor of Jesus in the lineage of the kings of Judah.', 'Matthew 1:14 (NLT)', 'Azor was the father of Zadok. Zadok was the father of Akim. Akim was the father of Eliud.', 'royal', 'royal_line', -310, 10600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('eliud', 'Eliud', 'Son of Akim', 'A descendant of David whose name appears in the genealogy of Jesus in Matthew''s Gospel.', 'Matthew 1:15 (NLT)', 'Eliud was the father of Eleazar. Eleazar was the father of Matthan. Matthan was the father of Jacob.', 'royal', 'royal_line', -310, 10800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('eleazar_matthew', 'Eleazar', 'Son of Eliud', 'An ancestor of Joseph, the husband of Mary, in the Davidic royal line.', 'Matthew 1:15 (NLT)', 'Eliud was the father of Eleazar. Eleazar was the father of Matthan. Matthan was the father of Jacob.', 'royal', 'royal_line', -310, 11000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('matthan', 'Matthan', 'Son of Eleazar', 'The grandfather of Joseph, the husband of Mary, in the royal genealogy of Jesus.', 'Matthew 1:15 (NLT)', 'Eliud was the father of Eleazar. Eleazar was the father of Matthan. Matthan was the father of Jacob.', 'royal', 'royal_line', -310, 11200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jacob_matthew', 'Jacob', 'Father of Joseph', 'The son of Matthan and father of Joseph the husband of Mary, representing the final generation before the birth of Christ in Matthew''s record.', 'Matthew 1:16 (NLT)', 'Jacob was the father of Joseph, the husband of Mary. Mary gave birth to Jesus, who is called the Messiah.', 'royal', 'royal_line', -310, 11400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('joseph_matthew', 'Joseph', 'Husband of Mary', 'A descendant of King David and a righteous man who served as the legal father of Jesus on earth.', 'Matthew 1:16 (NLT)', 'Jacob was the father of Joseph, the husband of Mary. Mary gave birth to Jesus, who is called the Messiah.', 'royal', 'royal_line', -310, 11600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('nathan_luke', 'Nathan', 'Son of David', 'A son of King David through whom the biological lineage of Jesus is traced in Luke''s Gospel.', 'Luke 3:31 (NLT)', 'Nathan was the son of David.', 'biological', 'biological_line', 10, 6600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('mattatha_luke', 'Mattatha', 'Son of Nathan', 'The son of Nathan and a grandson of King David.', 'Luke 3:31 (NLT)', 'Mattatha was the son of Nathan.', 'biological', 'biological_line', 10, 6800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('menna_luke', 'Menna', 'Son of Mattatha', 'An ancestor of Jesus in the biological line recorded by Luke.', 'Luke 3:31 (NLT)', 'Menna was the son of Mattatha.', 'biological', 'biological_line', 10, 7000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('melea_luke', 'Melea', 'Son of Menna', 'A descendant of David in the lineage leading to Jesus.', 'Luke 3:31 (NLT)', 'Melea was the son of Menna.', 'biological', 'biological_line', 10, 7200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('eliakim_luke', 'Eliakim', 'Son of Melea', 'A member of the Davidic line through Nathan, distinct from the Eliakim in Matthew''s royal line.', 'Luke 3:31 (NLT)', 'Eliakim was the son of Melea.', 'biological', 'biological_line', 10, 7400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jonam_luke', 'Jonam', 'Son of Eliakim', 'An ancestor of Jesus in the pre-exilic period of the Davidic lineage.', 'Luke 3:30 (NLT)', 'Jonam was the son of Eliakim.', 'biological', 'biological_line', 10, 7600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('joseph_luke_1', 'Joseph', 'Son of Jonam', 'A descendant of David through Nathan, not to be confused with Joseph the husband of Mary.', 'Luke 3:30 (NLT)', 'Joseph was the son of Jonam.', 'biological', 'biological_line', 10, 7800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('judah_luke', 'Judah', 'Son of Joseph', 'A member of the biological lineage of Jesus Christ as recorded in Luke.', 'Luke 3:30 (NLT)', 'Judah was the son of Joseph.', 'biological', 'biological_line', 10, 8000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('simeon_luke', 'Simeon', 'Son of Judah', 'An ancestor of Jesus in the line of Nathan.', 'Luke 3:30 (NLT)', 'Simeon was the son of Judah.', 'biological', 'biological_line', 10, 8200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('levi_luke_1', 'Levi', 'Son of Simeon', 'A member of the Davidic lineage, named after the forefather of the priestly tribe.', 'Luke 3:30 (NLT)', 'Levi was the son of Simeon.', 'biological', 'biological_line', 10, 8400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('matthat_luke_1', 'Matthat', 'Son of Levi', 'An ancestor in the genealogy of Jesus, the first of two by this name in Luke''s list.', 'Luke 3:29 (NLT)', 'Jorim was the son of Matthat. Matthat was the son of Levi.', 'biological', 'biological_line', 10, 8600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jorim_luke', 'Jorim', 'Son of Matthat', 'A descendant of Nathan and David in the lineage of Jesus.', 'Luke 3:29 (NLT)', 'Jorim was the son of Matthat.', 'biological', 'biological_line', 10, 8800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('eliezer_luke', 'Eliezer', 'Son of Jorim', 'An ancestor of Jesus mentioned in the biological genealogy.', 'Luke 3:29 (NLT)', 'Eliezer was the son of Jorim.', 'biological', 'biological_line', 10, 9000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('joshua_luke', 'Joshua', 'Son of Eliezer', 'A member of the Davidic line through Nathan, bearing the name of the great leader of Israel.', 'Luke 3:29 (NLT)', 'Joshua was the son of Eliezer.', 'biological', 'biological_line', 10, 9200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('er_luke', 'Er', 'Son of Joshua', 'An ancestor in the genealogy of Jesus Christ recorded by Luke.', 'Luke 3:29 (NLT)', 'Er was the son of Joshua.', 'biological', 'biological_line', 10, 9400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('elmadam_luke', 'Elmadam', 'Son of Er', 'A descendant of David in the lineage leading to Jesus.', 'Luke 3:28 (NLT)', 'Cosam was the son of Elmadam. Elmadam was the son of Er.', 'biological', 'biological_line', 10, 9600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('cosam_luke', 'Cosam', 'Son of Elmadam', 'An ancestor of Jesus mentioned in the biological record of Luke.', 'Luke 3:28 (NLT)', 'Cosam was the son of Elmadam.', 'biological', 'biological_line', 10, 9800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('addi_luke', 'Addi', 'Son of Cosam', 'A member of the lineage of David through Nathan.', 'Luke 3:28 (NLT)', 'Addi was the son of Cosam.', 'biological', 'biological_line', 10, 10000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('melki_luke_1', 'Melki', 'Son of Addi', 'The first of two ancestors named Melki in Luke''s genealogy.', 'Luke 3:28 (NLT)', 'Melki was the son of Addi.', 'biological', 'biological_line', 10, 10200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('neri_luke', 'Neri', 'Son of Melki', 'An ancestor of Jesus and the father of Shealtiel in the biological line.', 'Luke 3:27 (NLT)', 'Shealtiel was the son of Neri. Neri was the son of Melki.', 'biological', 'biological_line', 10, 10400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('shealtiel_luke', 'Shealtiel', 'Son of Neri', 'A key figure in the lineage who connected the line of Nathan to the line that would produce Zerubbabel.', 'Luke 3:27 (NLT)', 'Zerubbabel was the son of Shealtiel. Shealtiel was the son of Neri.', 'biological', 'biological_line', 10, 10600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('zerubbabel_luke', 'Zerubbabel', 'Son of Shealtiel', 'The leader of the return from Babylon, appearing in both genealogies of Jesus.', 'Luke 3:27 (NLT)', 'Rhesa was the son of Zerubbabel. Zerubbabel was the son of Shealtiel.', 'biological', 'biological_line', 10, 10800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('rhesa_luke', 'Rhesa', 'Son of Zerubbabel', 'The son of Zerubbabel and an ancestor of Jesus in the post-exilic period.', 'Luke 3:27 (NLT)', 'Rhesa was the son of Zerubbabel.', 'biological', 'biological_line', 10, 11000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('joanan_luke', 'Joanan', 'Son of Rhesa', 'An ancestor of Jesus in the biological genealogy recorded by Luke.', 'Luke 3:27 (NLT)', 'Joanan was the son of Rhesa.', 'biological', 'biological_line', 10, 11200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('joda_luke', 'Joda', 'Son of Joanan', 'A member of the Davidic line leading to Jesus.', 'Luke 3:26 (NLT)', 'Josech was the son of Joda. Joda was the son of Joanan.', 'biological', 'biological_line', 10, 11400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('josech_luke', 'Josech', 'Son of Joda', 'An ancestor of Jesus in the lineage of Nathan.', 'Luke 3:26 (NLT)', 'Josech was the son of Joda.', 'biological', 'biological_line', 10, 11600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('semein_luke', 'Semein', 'Son of Josech', 'A descendant of David in the genealogy of Jesus Christ.', 'Luke 3:26 (NLT)', 'Mattathias was the son of Semein. Semein was the son of Josech.', 'biological', 'biological_line', 10, 11800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('mattathias_luke_1', 'Mattathias', 'Son of Semein', 'The first of two ancestors named Mattathias in this section of the genealogy.', 'Luke 3:26 (NLT)', 'Maath was the son of Mattathias. Mattathias was the son of Semein.', 'biological', 'biological_line', 10, 12000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('maath_luke', 'Maath', 'Son of Mattathias', 'An ancestor of Jesus mentioned in the Gospel of Luke.', 'Luke 3:26 (NLT)', 'Maath was the son of Mattathias.', 'biological', 'biological_line', 10, 12200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('naggai_luke', 'Naggai', 'Son of Maath', 'A member of the lineage of Jesus Christ in the post-exilic period.', 'Luke 3:25 (NLT)', 'Esli was the son of Naggai. Naggai was the son of Maath.', 'biological', 'biological_line', 10, 12400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('esli_luke', 'Esli', 'Son of Naggai', 'An ancestor of Jesus in the Davidic line through Nathan.', 'Luke 3:25 (NLT)', 'Esli was the son of Naggai.', 'biological', 'biological_line', 10, 12600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('nahum_luke', 'Nahum', 'Son of Esli', 'A descendant of David in the genealogy recorded by Luke.', 'Luke 3:25 (NLT)', 'Amos was the son of Nahum. Nahum was the son of Esli.', 'biological', 'biological_line', 10, 12800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('amos_luke', 'Amos', 'Son of Nahum', 'An ancestor of Jesus Christ, not to be confused with the prophet Amos.', 'Luke 3:25 (NLT)', 'Amos was the son of Nahum.', 'biological', 'biological_line', 10, 13000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('mattathias_luke_2', 'Mattathias', 'Son of Amos', 'The second ancestor named Mattathias in Luke''s genealogy.', 'Luke 3:25 (NLT)', 'Joseph was the son of Mattathias. Mattathias was the son of Amos.', 'biological', 'biological_line', 10, 13200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('joseph_luke_2', 'Joseph', 'Son of Mattathias', 'Another ancestor named Joseph in the lineage between David and the Messiah.', 'Luke 3:24 (NLT)', 'Jannai was the son of Joseph. Joseph was the son of Mattathias.', 'biological', 'biological_line', 10, 13400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jannai_luke', 'Jannai', 'Son of Joseph', 'A member of the pre-Messianic lineage of Jesus.', 'Luke 3:24 (NLT)', 'Melki was the son of Jannai. Jannai was the son of Joseph.', 'biological', 'biological_line', 10, 13600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('melki_luke_2', 'Melki', 'Son of Jannai', 'The second ancestor named Melki in Luke''s list, appearing late in the genealogy.', 'Luke 3:24 (NLT)', 'Levi was the son of Melki. Melki was the son of Jannai.', 'biological', 'biological_line', 10, 13800);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('levi_luke_2', 'Levi', 'Son of Melki', 'The second ancestor named Levi in the lineage recorded by Luke.', 'Luke 3:24 (NLT)', 'Matthat was the son of Levi. Levi was the son of Melki.', 'biological', 'biological_line', 10, 14000);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('matthat_luke_2', 'Matthat', 'Son of Levi', 'The father of Heli and grandfather of Joseph in the biological lineage of Jesus.', 'Luke 3:24 (NLT)', 'Heli was the son of Matthat. Matthat was the son of Levi.', 'biological', 'biological_line', 10, 14200);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('heli_luke', 'Heli', 'Father of Joseph', 'The father of Joseph (often understood as Mary''s father, making him Joseph''s father-in-law) in Luke''s genealogy.', 'Luke 3:23 (NLT)', 'Joseph was the son of Heli.', 'biological', 'biological_line', 10, 14400);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('joseph_luke', 'Joseph', 'Husband of Mary', 'The legal father of Jesus, whose biological connection to David is traced through the line of Nathan in Luke''s Gospel.', 'Luke 3:23 (NLT)', 'Jesus was known as the son of Joseph. Joseph was the son of Heli.', 'biological', 'biological_line', 10, 14600);
INSERT INTO nodes (id, name, title, description, scripture_reference, scripture_text, lineage, epoch, x, y) VALUES ('jesus_unified', 'Jesus Christ', 'The Messiah, Son of God', 'The ultimate fulfillment of both the royal and biological lineages of David, the Savior of the world.', 'Matthew 1:16 / Luke 3:23 (NLT)', 'Mary gave birth to Jesus, who is called the Messiah.', 'royal', 'the_messiah', -150, 15000);
INSERT INTO edges (id, source, target) VALUES ('e-adam-seth', 'adam', 'seth');
INSERT INTO edges (id, source, target) VALUES ('e-seth-enosh', 'seth', 'enosh');
INSERT INTO edges (id, source, target) VALUES ('e-enosh-kenan', 'enosh', 'kenan');
INSERT INTO edges (id, source, target) VALUES ('e-kenan-mahalalel', 'kenan', 'mahalalel');
INSERT INTO edges (id, source, target) VALUES ('e-mahalalel-jared', 'mahalalel', 'jared');
INSERT INTO edges (id, source, target) VALUES ('e-jared-enoch', 'jared', 'enoch');
INSERT INTO edges (id, source, target) VALUES ('e-enoch-methuselah', 'enoch', 'methuselah');
INSERT INTO edges (id, source, target) VALUES ('e-methuselah-lamech', 'methuselah', 'lamech');
INSERT INTO edges (id, source, target) VALUES ('e-lamech-noah', 'lamech', 'noah');
INSERT INTO edges (id, source, target) VALUES ('e-noah-shem', 'noah', 'shem');
INSERT INTO edges (id, source, target) VALUES ('e-shem-arphaxad', 'shem', 'arphaxad');
INSERT INTO edges (id, source, target) VALUES ('e-arphaxad-shelah', 'arphaxad', 'shelah');
INSERT INTO edges (id, source, target) VALUES ('e-shelah-eber', 'shelah', 'eber');
INSERT INTO edges (id, source, target) VALUES ('e-eber-peleg', 'eber', 'peleg');
INSERT INTO edges (id, source, target) VALUES ('e-peleg-reu', 'peleg', 'reu');
INSERT INTO edges (id, source, target) VALUES ('e-reu-serug', 'reu', 'serug');
INSERT INTO edges (id, source, target) VALUES ('e-serug-nahor', 'serug', 'nahor');
INSERT INTO edges (id, source, target) VALUES ('e-nahor-terah', 'nahor', 'terah');
INSERT INTO edges (id, source, target) VALUES ('e-terah-abraham', 'terah', 'abraham');
INSERT INTO edges (id, source, target) VALUES ('e-abraham-isaac', 'abraham', 'isaac');
INSERT INTO edges (id, source, target) VALUES ('e-isaac-jacob', 'isaac', 'jacob');
INSERT INTO edges (id, source, target) VALUES ('e-jacob-judah', 'jacob', 'judah');
INSERT INTO edges (id, source, target) VALUES ('e-judah-perez', 'judah', 'perez');
INSERT INTO edges (id, source, target) VALUES ('e-perez-hezron', 'perez', 'hezron');
INSERT INTO edges (id, source, target) VALUES ('e-hezron-ram', 'hezron', 'ram');
INSERT INTO edges (id, source, target) VALUES ('e-ram-amminadab', 'ram', 'amminadab');
INSERT INTO edges (id, source, target) VALUES ('e-amminadab-nahshon', 'amminadab', 'nahshon');
INSERT INTO edges (id, source, target) VALUES ('e-nahshon-salmon', 'nahshon', 'salmon');
INSERT INTO edges (id, source, target) VALUES ('e-salmon-boaz', 'salmon', 'boaz');
INSERT INTO edges (id, source, target) VALUES ('e-boaz-obed', 'boaz', 'obed');
INSERT INTO edges (id, source, target) VALUES ('e-obed-jesse', 'obed', 'jesse');
INSERT INTO edges (id, source, target) VALUES ('e-jesse-david', 'jesse', 'david');
INSERT INTO edges (id, source, target) VALUES ('e-david-solomon', 'david', 'solomon');
INSERT INTO edges (id, source, target) VALUES ('e-solomon-rehoboam', 'solomon', 'rehoboam');
INSERT INTO edges (id, source, target) VALUES ('e-rehoboam-abijah', 'rehoboam', 'abijah');
INSERT INTO edges (id, source, target) VALUES ('e-abijah-asa', 'abijah', 'asa');
INSERT INTO edges (id, source, target) VALUES ('e-asa-jehoshaphat', 'asa', 'jehoshaphat');
INSERT INTO edges (id, source, target) VALUES ('e-jehoshaphat-jehoram', 'jehoshaphat', 'jehoram');
INSERT INTO edges (id, source, target) VALUES ('e-jehoram-uzziah', 'jehoram', 'uzziah');
INSERT INTO edges (id, source, target) VALUES ('e-uzziah-jotham', 'uzziah', 'jotham');
INSERT INTO edges (id, source, target) VALUES ('e-jotham-ahaz', 'jotham', 'ahaz');
INSERT INTO edges (id, source, target) VALUES ('e-ahaz-hezekiah', 'ahaz', 'hezekiah');
INSERT INTO edges (id, source, target) VALUES ('e-hezekiah-manasseh', 'hezekiah', 'manasseh');
INSERT INTO edges (id, source, target) VALUES ('e-manasseh-amon', 'manasseh', 'amon');
INSERT INTO edges (id, source, target) VALUES ('e-amon-josiah', 'amon', 'josiah');
INSERT INTO edges (id, source, target) VALUES ('e-josiah-jehoiachin', 'josiah', 'jehoiachin');
INSERT INTO edges (id, source, target) VALUES ('e-jehoiachin-shealtiel_matthew', 'jehoiachin', 'shealtiel_matthew');
INSERT INTO edges (id, source, target) VALUES ('e-shealtiel_matthew-zerubbabel_matthew', 'shealtiel_matthew', 'zerubbabel_matthew');
INSERT INTO edges (id, source, target) VALUES ('e-zerubbabel_matthew-abiud', 'zerubbabel_matthew', 'abiud');
INSERT INTO edges (id, source, target) VALUES ('e-abiud-eliakim_matthew', 'abiud', 'eliakim_matthew');
INSERT INTO edges (id, source, target) VALUES ('e-eliakim_matthew-azor', 'eliakim_matthew', 'azor');
INSERT INTO edges (id, source, target) VALUES ('e-azor-zadok_matthew', 'azor', 'zadok_matthew');
INSERT INTO edges (id, source, target) VALUES ('e-zadok_matthew-akim', 'zadok_matthew', 'akim');
INSERT INTO edges (id, source, target) VALUES ('e-akim-eliud', 'akim', 'eliud');
INSERT INTO edges (id, source, target) VALUES ('e-eliud-eleazar_matthew', 'eliud', 'eleazar_matthew');
INSERT INTO edges (id, source, target) VALUES ('e-eleazar_matthew-matthan', 'eleazar_matthew', 'matthan');
INSERT INTO edges (id, source, target) VALUES ('e-matthan-jacob_matthew', 'matthan', 'jacob_matthew');
INSERT INTO edges (id, source, target) VALUES ('e-jacob_matthew-joseph_matthew', 'jacob_matthew', 'joseph_matthew');
INSERT INTO edges (id, source, target) VALUES ('e-david-nathan_luke', 'david', 'nathan_luke');
INSERT INTO edges (id, source, target) VALUES ('e-nathan_luke-mattatha_luke', 'nathan_luke', 'mattatha_luke');
INSERT INTO edges (id, source, target) VALUES ('e-mattatha_luke-menna_luke', 'mattatha_luke', 'menna_luke');
INSERT INTO edges (id, source, target) VALUES ('e-menna_luke-melea_luke', 'menna_luke', 'melea_luke');
INSERT INTO edges (id, source, target) VALUES ('e-melea_luke-eliakim_luke', 'melea_luke', 'eliakim_luke');
INSERT INTO edges (id, source, target) VALUES ('e-eliakim_luke-jonam_luke', 'eliakim_luke', 'jonam_luke');
INSERT INTO edges (id, source, target) VALUES ('e-jonam_luke-joseph_luke_1', 'jonam_luke', 'joseph_luke_1');
INSERT INTO edges (id, source, target) VALUES ('e-joseph_luke_1-judah_luke', 'joseph_luke_1', 'judah_luke');
INSERT INTO edges (id, source, target) VALUES ('e-judah_luke-simeon_luke', 'judah_luke', 'simeon_luke');
INSERT INTO edges (id, source, target) VALUES ('e-simeon_luke-levi_luke_1', 'simeon_luke', 'levi_luke_1');
INSERT INTO edges (id, source, target) VALUES ('e-levi_luke_1-matthat_luke_1', 'levi_luke_1', 'matthat_luke_1');
INSERT INTO edges (id, source, target) VALUES ('e-matthat_luke_1-jorim_luke', 'matthat_luke_1', 'jorim_luke');
INSERT INTO edges (id, source, target) VALUES ('e-jorim_luke-eliezer_luke', 'jorim_luke', 'eliezer_luke');
INSERT INTO edges (id, source, target) VALUES ('e-eliezer_luke-joshua_luke', 'eliezer_luke', 'joshua_luke');
INSERT INTO edges (id, source, target) VALUES ('e-joshua_luke-er_luke', 'joshua_luke', 'er_luke');
INSERT INTO edges (id, source, target) VALUES ('e-er_luke-elmadam_luke', 'er_luke', 'elmadam_luke');
INSERT INTO edges (id, source, target) VALUES ('e-elmadam_luke-cosam_luke', 'elmadam_luke', 'cosam_luke');
INSERT INTO edges (id, source, target) VALUES ('e-cosam_luke-addi_luke', 'cosam_luke', 'addi_luke');
INSERT INTO edges (id, source, target) VALUES ('e-addi_luke-melki_luke_1', 'addi_luke', 'melki_luke_1');
INSERT INTO edges (id, source, target) VALUES ('e-melki_luke_1-neri_luke', 'melki_luke_1', 'neri_luke');
INSERT INTO edges (id, source, target) VALUES ('e-neri_luke-shealtiel_luke', 'neri_luke', 'shealtiel_luke');
INSERT INTO edges (id, source, target) VALUES ('e-shealtiel_luke-zerubbabel_luke', 'shealtiel_luke', 'zerubbabel_luke');
INSERT INTO edges (id, source, target) VALUES ('e-zerubbabel_luke-rhesa_luke', 'zerubbabel_luke', 'rhesa_luke');
INSERT INTO edges (id, source, target) VALUES ('e-rhesa_luke-joanan_luke', 'rhesa_luke', 'joanan_luke');
INSERT INTO edges (id, source, target) VALUES ('e-joanan_luke-joda_luke', 'joanan_luke', 'joda_luke');
INSERT INTO edges (id, source, target) VALUES ('e-joda_luke-josech_luke', 'joda_luke', 'josech_luke');
INSERT INTO edges (id, source, target) VALUES ('e-josech_luke-semein_luke', 'josech_luke', 'semein_luke');
INSERT INTO edges (id, source, target) VALUES ('e-semein_luke-mattathias_luke_1', 'semein_luke', 'mattathias_luke_1');
INSERT INTO edges (id, source, target) VALUES ('e-mattathias_luke_1-maath_luke', 'mattathias_luke_1', 'maath_luke');
INSERT INTO edges (id, source, target) VALUES ('e-maath_luke-naggai_luke', 'maath_luke', 'naggai_luke');
INSERT INTO edges (id, source, target) VALUES ('e-naggai_luke-esli_luke', 'naggai_luke', 'esli_luke');
INSERT INTO edges (id, source, target) VALUES ('e-esli_luke-nahum_luke', 'esli_luke', 'nahum_luke');
INSERT INTO edges (id, source, target) VALUES ('e-nahum_luke-amos_luke', 'nahum_luke', 'amos_luke');
INSERT INTO edges (id, source, target) VALUES ('e-amos_luke-mattathias_luke_2', 'amos_luke', 'mattathias_luke_2');
INSERT INTO edges (id, source, target) VALUES ('e-mattathias_luke_2-joseph_luke_2', 'mattathias_luke_2', 'joseph_luke_2');
INSERT INTO edges (id, source, target) VALUES ('e-joseph_luke_2-jannai_luke', 'joseph_luke_2', 'jannai_luke');
INSERT INTO edges (id, source, target) VALUES ('e-jannai_luke-melki_luke_2', 'jannai_luke', 'melki_luke_2');
INSERT INTO edges (id, source, target) VALUES ('e-melki_luke_2-levi_luke_2', 'melki_luke_2', 'levi_luke_2');
INSERT INTO edges (id, source, target) VALUES ('e-levi_luke_2-matthat_luke_2', 'levi_luke_2', 'matthat_luke_2');
INSERT INTO edges (id, source, target) VALUES ('e-matthat_luke_2-heli_luke', 'matthat_luke_2', 'heli_luke');
INSERT INTO edges (id, source, target) VALUES ('e-heli_luke-joseph_luke', 'heli_luke', 'joseph_luke');
INSERT INTO edges (id, source, target) VALUES ('e-joseph_matthew-jesus_unified', 'joseph_matthew', 'jesus_unified');
INSERT INTO edges (id, source, target) VALUES ('e-joseph_luke-jesus_unified', 'joseph_luke', 'jesus_unified');
